platform :ios, '13.0'

def flutter_install_all_ios_pods(flutter_application_path)
  # This helper function automatically installs all necessary iOS Pods for Flutter projects
  flutter_ios_podfile = File.join(flutter_application_path, 'Flutter', 'podhelper.rb')
  
  # Ensure the file exists before attempting to load it
  if File.exist?(flutter_ios_podfile)
    load flutter_ios_podfile
  else
    raise "flutter_install_all_ios_pods: Could not find podhelper.rb in #{flutter_application_path}/Flutter"
  end
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
